#!/bin/sh

set -e
TEMPFILE=$(mktemp -p "")
echo $TEMPFILE
if [ "$(uname -m)" = "sw_64" ];then
	trap "rm -rf $TEMPFILE" HUP INT QUIT TERM STOP EXIT
else
	trap "rm -rf $TEMPFILE" HUP INT QUIT TERM STOP PWR EXIT
fi

EDITOR=ed sensible-editor "$TEMPFILE" <<EOF
a
test
.
w
q
EOF
